Pivot -> core
GreenBlitz/Syncopa-Off-Season-2024 pull request #1
Opened 2024-09-25 20:25 UTC by NoamRosenberg08

2024-09-26 06:22 UTC, YHerm commented on src/main/java/frc/robot/subsystems/pivot/Pivot.java
> +    }
remove

2024-09-26 06:24 UTC, YHerm commented on src/main/java/frc/robot/subsystems/pivot/PivotConstants.java
> +                new Phoenix6AngleRequest(new PositionVoltage(0)),
use foc

2024-09-26 06:26 UTC, YHerm commented on src/main/java/frc/robot/subsystems/pivot/PivotConstants.java
> +                        )
move to function

2024-09-26 06:27 UTC, YHerm commented on src/main/java/frc/robot/subsystems/pivot/PivotConstants.java
> +
add generate config

2024-09-26 06:27 UTC, YHerm commented on src/main/java/frc/robot/subsystems/pivot/PivotCommands.java
> +    public Command setPosition(Rotation2d position) {
```suggestion
    public Command setTargetPosition(Rotation2d position) {
```

2024-09-26 06:27 UTC, YHerm commented on src/main/java/frc/robot/subsystems/pivot/PivotCommands.java
> +public class PivotCommands {
```suggestion
public class PivotCommandsBuilder {
```

2024-09-26 06:28 UTC, YHerm commented on src/main/java/frc/robot/subsystems/pivot/PivotCommands.java
> +    public PivotCommands(Pivot pivot) {
add command using joystick (supplier)

2024-09-26 06:28 UTC, YHerm commented on src/main/java/frc/robot/constants/IDs.java
> +		public static final Phoenix6DeviceID PIVOT_MOTOR_ID = new Phoenix6DeviceID(1, BusChain.CANIVORE);
find real

2024-09-26 06:29 UTC, YHerm commented on src/main/java/frc/robot/subsystems/pivot/Pivot.java
> +    private final ControllableMotor motor;
save the commands here as memeber

2024-09-26 06:29 UTC, YHerm commented on src/main/java/frc/robot/subsystems/pivot/PivotConstants.java
> +public class PivotConstants {
add factory and call this class real constants

2024-09-26 06:29 UTC, YHerm commented on src/main/java/frc/robot/subsystems/pivot/Pivot.java
> +    }
remo0ve

2024-09-26 06:29 UTC, YHerm commented on src/main/java/frc/robot/subsystems/pivot/Pivot.java
> +    public void stop() {
format

2024-09-26 09:44 UTC, bossyshrimp68 requested changes

2024-09-26 09:44 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/Pivot.java
> +            InputSignal... inputSignals
remove the ... or make the InputSignal generic

2024-09-26 09:44 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/Pivot.java
> +        this.positionRequest = positionRequest;
make these the same order as the parameters

2024-09-26 09:44 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/PivotConstants.java
> +        return new Pivot(
no

2024-09-26 19:33 UTC, YHerm commented on src/main/java/frc/robot/JoysticksBindings.java
> +        usedJoystick.B.whileTrue(robot.pivot.getPivotCommandsBuilder().setPosition(Rotation2d.fromDegrees(50)));
not in main and dont set  default command

2024-09-26 19:33 UTC, YHerm commented on src/main/java/frc/robot/Robot.java
> +	public Pivot pivot = PivotFactory.generatePivot("pivot");
private final and init in constructor

2024-09-26 19:33 UTC, YHerm commented on src/main/java/frc/robot/constants/GlobalConstants.java
> +	public static final double CANIVORE_UPDATE_FREQUENCY = 50;
remove and update branch

2024-09-26 19:34 UTC, YHerm commented on src/main/java/frc/robot/subsystems/pivot/Pivot.java
> +	private final MedianFilter resetFilter;
why???

2024-09-26 19:35 UTC, YHerm commented on src/main/java/frc/robot/subsystems/pivot/PivotFactory.java
> +                new Phoenix6AngleRequest(new PositionVoltage(0).withEnableFOC(true)),
why 100??

2024-09-26 19:38 UTC, YHerm commented on src/main/java/frc/robot/subsystems/pivot/PivotCommandsBuilder.java
> +		).withName("set position to" + position.getDegrees());
Set Position to:   "+

2024-09-26 22:16 UTC, bossyshrimp68 requested changes
a lot of small details, we need to decide a convention

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/JoysticksBindings.java
> +		usedJoystick.B.whileTrue(robot.pivot.getPivotCommandsBuilder().moveToPosition(Rotation2d.fromDegrees(50)));
delete

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/Robot.java
> +
delete

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/constants/IDs.java
> +		public static final Phoenix6DeviceID PIVOT_MOTOR_ID = new Phoenix6DeviceID(11, BusChain.CANIVORE);
we can also just call it PIVOT since its IDs.TalonFXs.PIVOT_MOTOR_ID but not important

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/Pivot.java
> +		}
should be a func, and why are you only checking the backwards?

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/PivotCommandsBuilder.java
> +	}
stop the one liners

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/Pivot.java
> +		motor.updateSignals(positionSignal);
why are you updating here?

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/Pivot.java
> +		motor.updateSignals(inputSignals);
i think its nicer as a separate func

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/PivotCommandsBuilder.java
> +			.withName("Set Supplied Power");
```suggestion
			.withName("Set power by supplier");
```

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/PivotCommandsBuilder.java
> +			.withName("Set Power to: " + power);
```suggestion
			.withName("Set power to: " + power);
```

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/PivotCommandsBuilder.java
> +		).withName("Move to: " + position);
```suggestion
		).withName("Move to position: " + position);
```

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/PivotCommandsBuilder.java
> +		).withName("Move to Supplier Position");
```suggestion
		).withName("Move to supplier position");
```

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/PivotConstants.java
> +
delete

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/PivotConstants.java
> +	public static final Rotation2d BACKWARD_ANGLE_LIMIT = Rotation2d.fromDegrees(17);
space

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/Pivot.java
> +		motor.resetPosition(PivotConstants.BACKWARD_ANGLE_LIMIT);
consider adding a RESET_POSITION constant or smth

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/factories/PivotFactory.java
> +	}
in intake i did this in RealIntakeConstants, we should decide on a way. same with IntakeStuff/PivotStuff

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/factories/PivotFactory.java
> +	public static Rotation2d getTolerance() {
why would the tolerance be different?

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/factories/PivotRealConstants.java
> +
delete

2024-09-26 22:16 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/factories/PivotFactory.java
> +	public static Pivot generatePivot(String logPath) {
save the log path in PivotConstants and remove the perameter

2024-09-27 08:00 UTC, bossyshrimp68 approved these changes, later dismissed

2024-09-27 08:00 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/pivot/factory/RealPivotConstants.java
> +			new Alert(Alert.AlertType.WARNING, logPath + "ConfigurationFail").report();
error

2024-09-27 09:20 UTC, bossyshrimp68 approved these changes

2024-09-27 09:21 UTC, merged