States -> core
GreenBlitz/Syncopa-Off-Season-2024 pull request #16
Opened 2024-09-28 21:57 UTC by YHerm

2024-10-02 13:37 UTC, drorta commented on src/main/java/frc/robot/subsystems/roller/RollerCommandsBuilder.java
> +		return new InitExecuteCommand(
runcommand?

2024-10-02 13:44 UTC, drorta submitted a review, later dismissed

2024-10-03 08:25 UTC, bossyshrimp68 requested changes

2024-10-03 08:25 UTC, bossyshrimp68 commented on src/main/java/frc/robot/JoysticksBindings.java
> +		usedJoystick.L1.whileTrue(robot.getRoller().getCommandsBuilder().setPower(() -> usedJoystick.getAxisValue(Axis.LEFT_Y) * 0.7));
Test buttons/magic num?

2024-10-03 08:25 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/elbow/ElbowCommandsBuilder.java
> -			() -> elbow.isAtAngle(angle, tolerance),
If we decide to only us3 .until we should delete isFinished

2024-10-03 08:25 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelState.java
> +	private final Rotation2d shootingVelocity;
Just velocity will do

2024-10-03 08:25 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/funnel/FunnelCommandsBuilder.java
>      //@formatter:on
Put this last

2024-10-03 08:25 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/swerve/Swerve.java
> -		this.savedState = state;
Why not this.

2024-10-03 08:25 UTC, bossyshrimp68 commented on src/main/java/frc/robot/superstructure/Superstructure.java
> +		boolean isPivotReady = robot.getPivot().isAtPosition(PivotState.TRANSFER.getTargetPosition(), Tolerances.PIVOT_POSITION_TOLERANCE);
Why do we want a tolerance selection option?

2024-10-03 08:25 UTC, bossyshrimp68 commented on src/main/java/frc/robot/superstructure/Superstructure.java
> +				).withTimeout(0.475)//.until(this::isObjectInFunnel)
Is the bb fixed yet? Maybe save this numbers just in case

2024-10-03 08:27 UTC, YHerm commented on src/main/java/frc/robot/superstructure/Superstructure.java
> +				).withTimeout(0.475)//.until(this::isObjectInFunnel)
no

2024-10-03 08:27 UTC, YHerm commented on src/main/java/frc/robot/superstructure/Superstructure.java
> +		boolean isPivotReady = robot.getPivot().isAtPosition(PivotState.TRANSFER.getTargetPosition(), Tolerances.PIVOT_POSITION_TOLERANCE);
if i want at score in arm less accuracy but in transfer more

2024-10-03 08:28 UTC, YHerm commented on src/main/java/frc/robot/subsystems/swerve/Swerve.java
> -		this.savedState = state;
no in constructor (that not the convention now

2024-10-03 09:05 UTC, NoamRosenberg08 submitted a review, later dismissed

2024-10-03 14:06 UTC, bossyshrimp68 commented on src/main/java/frc/robot/superstructure/Superstructure.java
> +				).withTimeout(0.475)//.until(this::isObjectInFunnel)
Still save that number in a const

2024-10-03 14:11 UTC, merged