Flywheel -> core
GreenBlitz/Syncopa-Off-Season-2024 pull request #2
Opened 2024-09-25 20:26 UTC by NoamRosenberg08

2024-09-25 21:29 UTC, ItayKauff commented
Shooter go brrrrrrrrrrrrrrrrrrrrrrrrr

2024-09-26 11:46 UTC, YHerm commented on src/main/java/frc/robot/subsystems/flywheel/Flywheel.java
> +            InputSignal leftVelocitySignal,
type

2024-09-26 11:46 UTC, YHerm commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelCommands.java
> +    public FlywheelCommands(Flywheel flywheel) {
add command with power supplied

2024-09-26 11:47 UTC, YHerm commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelCommands.java
> +                },
bing bong

2024-09-26 11:50 UTC, YHerm commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelCommands.java
> +                flywheel
add is at velocities maybe, and dont stop (i think it will be easier to use in sequnces)

2024-09-26 17:27 UTC, greenblitz4590 commented on src/main/java/frc/robot/constants/IDs.java
> +		public static final Phoenix6DeviceID LEFT_FLYWHEEL = new Phoenix6DeviceID(1, BusChain.ROBORIO);
i dont think they have the same id

2024-09-26 17:27 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/flywheel/Flywheel.java
> +
space

2024-09-26 17:28 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/flywheel/Flywheel.java
> +		isAtVelocities(Rotation2d rightFlywheelExpectedVelocity, Rotation2d leftFlywheelExpectedVelocity, Rotation2d velocityTolerance) {
format off

2024-09-26 17:28 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/flywheel/Flywheel.java
> +	}
move up

2024-09-26 17:29 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/flywheel/Flywheel.java
> +		this.commandsBuilder = new FlywheelCommandsBuilder(this);
add update

2024-09-26 17:29 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelCommandsBuilder.java
> +	}
get tolerance

2024-09-26 17:32 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelConstants.java
> +	protected static final double REFRESH_HERTZ = 50;
there is const in gloabl constants

2024-09-26 17:33 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelConstants.java
> +
use funcs instead of static vars

2024-09-26 17:34 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelFactory.java
> +		);
move this to the constants and her hav e only constants.generateFlywheels

2024-09-26 17:34 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelFactory.java
> +            default -> null;
case SIMULATION

2024-09-26 17:35 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelFactory.java
> +    public static Flywheel generateFlywheel(RobotType type, String logPath){
use Robot.ROBOT_TYPE

2024-09-26 17:35 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelFactory.java
> +			new InputSignal[] {}
why???

2024-09-26 17:36 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelCommandsBuilder.java
> +	private Flywheel flywheel;
final

2024-09-26 17:37 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelCommandsBuilder.java
> +			() -> false,
add isAt velocites as is finished and dont stop

2024-09-26 17:54 UTC, greenblitz4590 requested changes
Add in robot

2024-09-26 18:11 UTC, greenblitz4590 commented on src/main/java/frc/robot/Robot.java
> +
add flywheel

2024-09-26 18:15 UTC, YoniKiriaty commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelFactory.java
> +            default -> null;
what should i put in case simulation?

2024-09-26 19:15 UTC, YHerm commented on src/main/java/frc/robot/Robot.java
> +	private Flywheel flywheel = FlywheelFactory.generateFlywheel("Flywheel/");
final and init in constructor

2024-09-26 19:16 UTC, YHerm commented on src/main/java/frc/robot/constants/GlobalConstants.java
> +	public static final double ROBORIO_CANBUS_UPDATE_FREQUENCY = 50;
remove and update branch

2024-09-26 19:18 UTC, YHerm commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelCommandsBuilder.java
> +			() -> flywheel.setTargetVelocities(rightVelocity, leftVelocity),
move to init

2024-09-26 19:19 UTC, YHerm commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelCommandsBuilder.java
> +		);
fix it

2024-09-26 19:20 UTC, YHerm commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelFactory.java
> +			new Phoenix6AngleRequest(new VelocityVoltage(0)),
FOC

2024-09-26 19:29 UTC, YHerm commented on src/main/java/frc/robot/subsystems/flywheel/Flywheel.java
> +				.isNear(leftFlywheelExpectedVelocity.getRotations(), leftVelocityTolerance.getRotations(), leftVelocityTolerance.getRotations());
split to vars

2024-09-26 19:30 UTC, YHerm commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelCommandsBuilder.java
> +	public Command setPowersBySuppliers(Supplier<Rotation2d> rightVelocity, Supplier<Rotation2d> leftVelocity) {
overload th setPOWERS

2024-09-26 19:30 UTC, YHerm commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelFactory.java
> +	private static Flywheel getRealFlywheel(String logPath) {
move this to real constants

2024-09-26 19:31 UTC, YHerm commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelFactory.java
> +			FlywheelRealConstants.generateSignal(rightMotorWrapper.getVelocity()),
don't generte twice here and in second

2024-09-27 09:31 UTC, bossyshrimp68 submitted a review, later dismissed

2024-09-27 09:39 UTC, bossyshrimp68 approved these changes

2024-09-27 09:39 UTC, merged