Arm Intake/Outtake -> wrist
GreenBlitz/Syncopa-Off-Season-2024 pull request #35
Opened 2024-10-04 19:30 UTC by YHerm

2024-10-05 15:21 UTC, bossyshrimp68 approved these changes, later dismissed

2024-10-05 19:13 UTC, NoamRosenberg08 requested changes

2024-10-05 19:13 UTC, NoamRosenberg08 commented on src/main/java/frc/robot/superstructure/Superstructure.java
> +				).withTimeout(0.5),////.until(this::isObjectInRoller)
magic number

2024-10-07 14:54 UTC, bossyshrimp68 submitted a review, later dismissed

2024-10-07 14:54 UTC, bossyshrimp68 commented on src/main/java/frc/robot/superstructure/Timeouts.java
> +public class Timeouts {
I prefer spaces, and add a comment that this is in seconds or smth

2024-10-07 17:19 UTC, merged